from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
service=(ROOT/'app/src/main/java/com/socialaiassistant/keyboard/context/SocialAiAccessibilityService.kt').read_text()
a11y=(ROOT/'docs/play-store/accessibility-declaration.md').read_text()
privacy=(ROOT/'docs/privacy/context-access-disclosure.md').read_text()
checks=[]
def req(n,o): checks.append((n,bool(o)))
req('service implements flight sink', 'AccessibilityService(), BubbleFlightSink' in service)
req('service registers bus', 'BubbleFlightBus.register(this)' in service and 'override fun onServiceConnected()' in service)
req('service unregisters bus', 'BubbleFlightBus.unregister(this)' in service)
req('overlay renderer created', 'BubbleFlightOverlayRenderer(AccessibilityBubbleOverlayWindowHost(this))' in service)
req('editable target stored transiently', 'latestBubbleEditableTarget: BubbleFlightTarget?' in service)
req('geometry before context consent gate', service.find('updateBubbleEditableTarget(safeEvent, packageName)') != -1 and service.find('updateBubbleEditableTarget(safeEvent, packageName)') < service.find('if (!ContextAccessGate.allowed.value)'))
req('editable focus fallback', 'findFocus(AccessibilityNodeInfo.FOCUS_INPUT)' in service)
req('password rejected', 'node.isPassword' in service)
req('bounds only target', 'getBoundsInScreen(bounds)' in service and 'BubbleAccessibilityTargetMapper.pointInside' in service)
req('no node retained', 'latestBubbleEditableNode' not in service)
req('current session validated on submit', 'activeBubbleEditorToken()' in service and 'if (activeEditor != request.editor)' in service)
req('resolver exact then fallback', 'exact = request.exactTarget' in service and 'fallback = latestBubbleEditableTarget' in service)
req('submit falls back to local when unresolved', ') ?: return false' in service)
req('renderer retarget wired', 'bubbleOverlayRenderer?.retarget(flightId, target) == true' in service)
req('cancel clears target', 'latestBubbleEditableTarget = null' in service)
req('accessibility disclosure bubble bounds', 'Bubble Key' in a11y and 'editable field bounds' in a11y)
req('privacy disclosure no persistence', 'Bubble Flight' in privacy and 'does not persist' in privacy)
req('disclosure no draw over apps', 'draw-over-other-apps' in a11y.lower() or 'draw over other apps' in a11y.lower())
for n,o in checks: print(('PASS' if o else 'FAIL')+': '+n)
print(f"Stage 24.1 Task 4 contract: {sum(o for _,o in checks)}/{len(checks)} PASS")
if not all(o for _,o in checks): raise SystemExit(1)
